language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-get update -q
  - sudo apt-get install --only-upgrade autoconf automake glibtool
install:
  - ./autogen.sh
script: 
  - ./configure && make && make check
notifications:
  email:
    on_success: always
    on_failure: always
